consuldemocracy/installer

roles/capistrano/tasks/main.yml, roles/capistrano/templates/deploy.rb
References
===
**Issue:** https://github.com/consul/installer/issues/12
What
===
Removing a duplicate capistrano action to clone the repo
Why
===
To be able to run the playbook multiple times in a single server
Notes
===
The initial purpose of this action was to clone the repo in a faster way, we can review it later on :relieved:
=> Make playbook inmutable

roles/capistrano/tasks/main.yml
What
===
- [1] Copy existing `secrets.example.yml`
- [2] Use CONSUL's [installer branch](https://github.com/consul/consul/compare/installer?expand=1)
Why
===
- [1] We forgot to run the playbook one last time in a blank server, and the location of the `secrets.example.yml` was using capistrano's `current` directory, which does not exist at [this point](https://github.com/consul/installer/compare/installer-branch?expand=1#diff-7ce018e7265aba4e90b399630e5ea4b1R74) in the playbook
- [2] The production `secrets` do not include a `secret_token`, this makes unicorn throw an error when starting the application. In CONSUL's installer branch we are using a default secret_token which _fixes_ the problem. Indeed we should generate a random secret token for every installation here is the …
=> Deploy using temporary installer branch in CONSUL

roles/capistrano/tasks/main.yml
What
===
Set permissions for local capistrano log file
Why
===
It was giving an error when running deploys
=> Set permissions for capistrano logs

roles/capistrano/templates/deploy.rb
What
===
Restart unicorn after a deploy
Why
===
To see the new changes deployed
Note
===
We should use variables instead of hardcoding static paths, all in it's due time 😌
=> Restart unicorn after a deploy

roles/capistrano/tasks/main.yml
What
===
Add group write permissions for capistrano files
Why
===
It was giving an permission error to some users when doing the initial deploy
=> Add group write permissions for capistrano files

group_vars/all, roles/capistrano/tasks/main.yml, roles/rails/templates/production.rb
References
===
**Issue: https://github.com/consul/installer/issues/7**
What
===
- Adds SMTP configuration to production.rb
- Add placeholder variables for SMTP configuration
- Copy production.rb template to correct capistrano deploy path
=> Add SMTP configuration

roles/rails/templates/production.rb
Context
===
SSL configuration to redirect traffic to https is not ready yet
What
===
- Deactivate ssl configuration for production environments until it is configured
- Lower production log level to debug until everything is running smoothly 😌
=> Deactivate SSL configuration

consul.yml, roles/ssl/tasks/main.yml
What
===
Use http instead of https as the default for now
Why
===
Still need to setup a default SSL certificate to make it all work with https
Let's Encrypt seems like the best option https://github.com/consul/installer/issues/8
=> Use http instead of https as the default

consul.yml, roles/queue/tasks/main.yml, roles/queue/templates/delayed_job_config.rb
Context
===
We use a queue to send emails and run other long processes asynchronously, that would cause a timeout if run synchronously
What
===
Deactivating for now, as it's not necessary for the initial setup 
But should definitely be reactivated[1] before launching to make the user experience more responsive :relieved:
[1] https://github.com/collectiveidea/delayed_job#running-jobs
=> Deactivate queue by default

roles/system/tasks/tools.yml
What
====
Install system library `ruby-dev`
Why
===
We were getting an error when installing the Nokogiri gem
Thanks ❤️ 
===
Thanks to @jesuxgslp for [pointing this out](https://github.com/consul/installer/issues/42#issue-336317190)! 🙏
Thanks to @warringaa for [the fix](https://github.com/consul/installer/issues/42#issuecomment-417646329)! :clap:
And @TheCoffeMaker for [verifying it](https://github.com/consul/installer/issues/42#issuecomment-422480990)! 👍
=> Fix Nokogiri dependecy

roles/system/tasks/main.yml
What
===
Update Nodejs from 4.x to 6.x
Why
===
We were getting an error when when precompiling assets:
`Autoprefixer doesn't support Node v4.2.6. Update it`
Probably due to the [recent gem update in CONSUL in the Autoprefixer gem](https://github.com/consul/consul/pull/2881)
Thanks ❤️
===
Thanks to @TheCoffeMaker [for pointing this out](https://github.com/consul/installer/issues/42#issuecomment-422480990)! :raised_hands:
=> Fix Precompile Assets task

README.md
We are now getting an error, at least from Digital Ocean servers, saying that it can't find Python 2 in the default packages when trying to install it with `sudo apt-get -y install python-simplejson`.
```
TASK [Gathering Facts] ********************************************************************************************************
fatal: [206.189.24.183]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 206.189.24.183 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}
```
Fix error by updating package versions before trying to install Python 2.
=> Update README with package version update

group_vars/all
Objetives
===
We were using a private token from a Sendgrid account in the configuration variables for SMTP. Removing it.
=> Remove Sendgrid's SMTP token

group_vars/all
Context
===
There seems to be a [bug](https://github.com/rvm/rvm/issues/4345) in the latest rvm version (1.29.5) which is preventing rvm's signatures from being verified. And thus stopping CONSUL's Ansible script from completing successfully.
The Ansible script works fine using rvm's `master` branch as it has already been [fixed there](https://github.com/rvm/rvm/issues/4345#issuecomment-378521820)
However the script works fine too using the previous stable version 1.29.4
Objectives
===
Downgrades rvm version from 1.29.5 to 1.29.4 to make the Ansible script complete successfully.
=> Downgrade to rvm version 1.29.4

roles/capistrano/tasks/main.yml
Context
===
DelayedJobs is a queue system to send emails asynchronously. It was partially implemented and causing some problems where emails were being stored in the queue and not being delivered. 
Objectives
===
Disable DelayedJobs by default after executing the Capistrano role.
=> Disable DelayedJobs for the Capistrano role

group_vars/all
Context
===
When executing the script a second time, RVM was trying to update to a [buggy release](https://github.com/consul/installer/pull/63) making the script not complete successfully.
Objectives
===
Maintain RMV in version 1.29.4 and do not auto update to 1.29.5 in subsequent runs of the script.
=> Disable RVM auto updates

.gitignore, README.md, consul.yml
No need to specify a group, since the users are most likely going to be dealing with just one server.
=> simplify host configuration

roles/system/tasks/main.yml
Apt can run in the background - commonly for automatic upgrades - which can cause an error when trying to run it in the foreground simultaneously. Add a check for the lock before running `apt` commands.
=> wait for apt automatic upgrades

README.md
In PaaS section, the Google App Engine link was redirecting to the Azure App Service
=> Small link fix in README.md

app.yml, db.yml, group_vars/all, roles/capistrano/tasks/main.yml, roles/capistrano/templates/consul_vhost.conf, roles/capistrano/templates/unicorn.rb, roles/nginx/tasks/main.yml, roles/nginx/templates/consul_vhost.conf, roles/queue/tasks/main.yml, roles/rails/tasks/main.yml, roles/rails/templates/database.yml, roles/system/tasks/locale.yml, roles/unicorn/tasks/main.yml, roles/unicorn/templates/unicorn.rb, roles/user/tasks/main.yml
**PR:** [Add documentation on how to setup without root access](https://github.com/consul/installer/issues/62)
There was still some code that had a hardcoded value for the deploy user.
Use a variable `deploy_user` instead of a hardcoded `deploy` value.
=> Use variable for the deploy user

app.yml, consul.yml, system.yml, user.yml
**PR:** [Add documentation on how to setup without root access](https://github.com/consul/installer/issues/62)
Some roles need to be executed first and be used by later roles.
- The `user` role includes the creation of the user that will install all libraries, so the user role should be run first.
- The `system` role includes general system upgrades, they should be run next.
=> Run system and user roles at the beginning

README.md, group_vars/all, user.yml
**PR:** [Add documentation on how to setup without root access](https://github.com/consul/installer/issues/62)
Some users do not have root access to their servers.
Allow skipping the initial `root` login and creation of a `deploy` user. 
This will allow system administrators to manually create any user with sudo privileges and use it as the user that will login and install all libraries in the server.
=> Add option to skip root login

roles/system/tasks/main.yml
Sometimes the installer gets stuck waiting for system updates to occur.
Remove the code that is causing this. Let's see if the [initial problem](https://github.com/consul/installer/pull/83) that created the need to add this change comes back.
=> Do not wait for system updates

roles/email/tasks/main.yml
**Issue** https://github.com/consul/installer/issues/95
With the addition of Rails 5 we have added more configuration options to `produciton.rb` creating a conflict in the production.rb configuration file.
Fix error when staring Unicorn due to syntax error in`production.rb` SMTP configuration
=> Make SMTP reg exp more robust

group_vars/all, roles/capistrano/tasks/main.yml, roles/email/tasks/main.yml, roles/rails/tasks/main.yml, roles/rails/templates/database.yml, roles/rails/templates/secrets.yml, roles/ssl/tasks/main.yml, roles/unicorn/tasks/main.yml
With the addition of [continuos integration](https://github.com/consul/installer/pull/97) and an upcoming PR to setup staging environments, it is necessary to prepare the Installer for multiple environments (`production`, `staging` and `test`).
Update variables that where hardcoded for a `production` environment to be dynamically generated using an `environment` variable.
=> Make variables environment agnostic

ansible.cfg
It is hard to follow what the installer is doing due the output not being formatted.
Format the standard Ansible output in yaml format.
**Before**
```
TASK [rails : Install gems (this may take a few minutes)] *********************************************************************
changed: [206.189.228.1] => {"changed": true, "cmd": "source /home/deploy/.rvm/scripts/rvm && bundle install", "delta": "0:01:49.362598", "end": "2019-05-10 14:18:32.071122", "rc": 0, "start": "2019-05-10 14:16:42.708524", "stderr": "", "stderr_lines": [], "stdout": "Fetching gem metadata from https://rails-assets.org/..\nFetching gem metadata from https://rubygems.org/...........\nFetching https://github.com/phatworx/devise_security_extension.git\nFetching gem metadata from https://rails-assets.org/..\nFetching …
```
=> Use yaml as default stdout format

roles/postgresql/tasks/main.yml
Fixes #104.
Otherwise, the postgres extensions "pg_trgm" and "unaccent" cannot be installed.
=> Add postgresql-contrib to be able to install postgres extensions.

roles/system/tasks/main.yml
Many Ubuntu server images have preinstalled Apache2 web server and configured to be running and using port 80.
This will result in an error when trying to install/configure nginx web server.
- Make sure apache is not installed/running before installing ngnix web server to avoid errors.
=> Make sure Apache web server is not installed/running

ansible.cfg
We're getting an error when running the installer with Ansible 2.8.7 on some servers:
```
TASK [postgresql : Create PostgreSQL database] **************************************************************************************************************
fatal: [146.0.40.30]: FAILED! => 
msg: |-
Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1570730167.47-95324634845843/': Operation not permitted
chown: changing ownership of '/var/tmp/ansible-tmp-1570730167.47-95324634845843/AnsiballZ_postgresql_db.py': Operation not permitted
}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
```
The ansible …
=> Allow world readable tmp files

README.md, app.yml, capistrano.yml, group_vars/all, roles/capistrano/tasks/main.yml, roles/folder_structure/tasks/main.yml, roles/rails/tasks/main.yml, roles/rails/templates/secrets.yml
* Closes #21
* Closes #81
Right now, we're generating a default "change_me" secret key base, and expect users to change it manually. Furthermore, we overwrite this key when we add capistrano.
* Generate a secure secret key base during the installation process and add it to `secrets.yml`
* Simplify installing capistrano, so we don't overwrite the secret key
Running the installer a second time will overwrite the generated secret key. This might or might not be the expected behaviour.
=> Generate secret key base automatically

app.yml
Executing role `nginx` before `letsencrypt` will result in the following error:
```
TASK [nginx : Restart Nginx] ***************************************************
fatal: [localhost]: FAILED! => changed=false 
msg: |-
Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
```
The output of `systemctl status nginx.service` states:
```
nginx[17087]: nginx: [emerg] open() "/etc/letsencrypt/options-ssl-nginx.conf" failed (2: No such file or directory) in /etc/nginx/sites-enabled/default:18
```
Changing the order of execution of the roles fixes the issue
=> Execute role lestencrypt before role nginx

galaxy/geerlingguy.memcached/tasks/main.yml
The "installed" state is deprecated and has been removed in some versions of Ansible.
=> Use "present" instead of "installed" as apt state

roles/folder_structure/tasks/main.yml
Simplify code and make it more stable.
With previous code:
- If the file/folder was not present the installer will throw an error and stop the execution.
- If the file/folder was present we will still get an Ansible warning:
```
[WARNING]: Consider using the file module with state=absent rather than running rm.
```
=> Use file module to delete file and folder

roles/nginx/templates/consul_vhost.j2
In the last versions of Consul, it is possible to set the size of image and file uploads to any value in the settings.
However, when using this installer, nginx sets a default limit of 1MB.
This PR sets a value of 32MB.
=> Increase nginx file size limit for uploads to 32M

.travis.yml, README.md, group_vars/all, hosts.example, user.yml
* Make it possible for users without sudo privileges on their local machine to run the playbook
* Simplify running the installer with no root access
=> Don't require sudo to run the playbook

roles/rails/tasks/main.yml
* Closes #136
Generate the secret running the rake task in the right environment. Otherwise we might get errors because we don't install gems for the development environment.
=> Fix environment for the rake secret task

roles/email/tasks/main.yml
* Closes #139
* Depends on consul/consul#3871
Fix a bug which caused `ActionMailer` not to correctly recognize the options in `secrets.yml`.
=> Use symbols instead of strings for SMTP settings

README.md
Update 'How to setup Capistrano' screencast, cutting out of the screencast the parts that had become obsolete.
- **Deprecated screencast**: https://www.youtube.com/watch?v=SgJzJ-clIrQ&t=1s
- **New screencast**: https://www.youtube.com/watch?v=ZCfPz_c_H6g
=> Update 'How to setup Capistrano' screencast

roles/rails/tasks/main.yml
* Closes #144
CONSUL automatically executes whenever when deploying with Capistrano. However, we were not configuring it during the installation.
Generate the crontab during the installation, so the scheduled tasks are executed properly even before configuring capistrano.
=> Generate crontab with whenever

galaxy/rvm.ruby/tasks/rubies.yml
* Related to consul/consul#3931
Using the latest bundler we got a deprecation warning when adding Capistrano. This warning might turn into an error in the future:
```
[DEPRECATED] The `--deployment` flag is deprecated because it relies on
being remembered across bundler invocations, which bundler will no
longer do in future versions.
```
Use the same version of Bundler we used to generate our Gemfile.lock.
We could also upgrade to bundler 2.x, but since we're using Ruby 2.4, and Ruby 2.6 comes with bundler 1.17, we've decided to keep this version.
This change requires changing a galaxy, which is something we should generally try to avoid. I haven't found a way to do it while keeping the galaxy as it is by default.
=> Specify which bundler version to install

roles/rails/templates/database.yml
We were configuring the database name in two places, meaning the installer wouldn't work if someone wanted to change the database name and forgot to change the name in both places.
Configure the database name in only one place.
=> Reuse database name variable

group_vars/all, roles/rails/tasks/main.yml
* Closes #152
We were assuming the application name is `consul`, and were writing it in several places, meaning if someone wanted a different name, they'd have to change it in all those places.
Configure the appication name in only one place
=> Reuse app name variable

README.md, roles/queue/tasks/main.yml, roles/rails/templates/database.yml, roles/specs/tasks/main.yml
Sending emails takes a few precious seconds which can slow down the response time for users. To speed things up we can use a queue to send emails asynchronously in the background. 
The queue is also very useful for long running tasks such as sending newsletters to thousands of users or processing signature sheets.
Configure queue using [DelayedJobs](https://github.com/collectiveidea/delayed_job).
~We should add a cron script to start the DelayedJob queue after a reboot. For now deploying the application will start the queue after a reboot~ (done in  #147 and consul/consul#3859)
=> Add DelayedJobs configuration

.travis.yml, app.yml, group_vars/all, roles/errbit/tasks/main.yml, roles/errbit/templates/errbit.example.com, roles/letsencrypt/tasks/main.yml, roles/mongodb/tasks/main.yml, roles/nginx/templates/consul_vhost.j2, roles/specs/tasks/main.yml
* Errbit support in CONSUL was added in consul/consul#3624
* The option to install Errbit is still experimental and so it isn't enabled by default
* If your DNS configuration doesn't automatically handle subdomains, you have to add an entry for the `errbit` subdomain
* During the installation process, a password for the Errbit user is generated and shown in the installer's output messages; make sure to write it down or you'll have to run  `RAILS_ENV=production bin/rake errbit:bootstrap` manually to generate it again
=> Add experimental Errbit support

README.md
* Closes #158
* Fix a path in the README file which pointed to the wrong folder
* Use the `-e` option in the `rails c` command, since not using it is deprecated in Rails 5.2 (although we still use Rails 5.1)
=> Fix path to current release folder in README

README.md
The domain travis-ci.org will stop working on December 31st, 2020, so we've now using travis-ci.com for continuous integration.
Update the Travis badge so it points to the URL we now use to run our test suite.
=> Update Travis badge to use travis-ci.com

README.md
Since  #131 `sudo` is not needed anymore.
=> Remove sudo from playbook command

.travis.yml, README.md, ansible.cfg, roles/letsencrypt/tasks/main.yml, roles/postgresql/tasks/main.yml
* [Support for Python 2 ended on January the 1st, 2020](https://pythonclock.org/)
* Use a supported Python version to run Ansible
* Use the default Python version in modern distributions
* For now we're using Python 3.6 in our CI because it's the oldest supported release and the one Ubuntu 18.04 shipped with.
=> Use Python 3 instead of Python 2

.github/workflows/tests.yml, roles/system/tasks/main.yml, roles/user/handlers/main.yml, roles/user/tasks/main.yml
* Closes #154
Make it possible to install CONSUL on servers running Ubuntu 20.04.
We're getting many Ansible warnings in our CI regarding using world-readable permissions for temporary files. They aren't related to using Ubuntu 20.04 but to the fact that the build for this distribution uses a more recent Ansible version. AFAIK they can safely be ignored, as mentioned in pull request #112.
=> Add Ubuntu 20.04 compatibility

roles/rails/tasks/main.yml
* CONSUL changed the `secrets.yml` file in consul/consul#4438
We're preparing to release CONSUL version 1.3, which added a change to the default secrets.yml file in order to avoid any chances of using an empty secret key base.
Make the installer compatible with both CONSUL 1.2.0 and CONSUL 1.3.0
=> Add compatibility with CONSUL 1.3

user.yml
Some server providers like Amazon provide Ubuntu images with a root privileged user named `ubuntu` instead of `root`, also Vagrant Ubuntu boxes provide a user named `vagrant`.
When I run the installer with any ansible_user different than `root`, the deploy user creation step is always ignored, and the installer crashes at following steps.
This will allow creating the `deploy` user for any `ansible_user` we use except when the `ansible_user` is the `deploy` user.
=> Create deploy user when using a custom ansible_user

README.md, roles/folder_structure/tasks/main.yml
* In order to run `bundle install`, we need to include the changes in consul/consul#4444
This is a temporary change until the situation with mimemagic is solved and we release version 1.3.
=> Install CONSUL's master branch

README.md
* Closes #173
Make it easier to undestand how to edit the `config/deploy-secrets.yml` file.
=> Add context to deployment instructions 

galaxy/rvm.ruby/tasks/rubies.yml
* CONSUL uses Ruby 2.6 since consul/consul#4209 
* The installer uses a version of CONSUL using Ruby 2.6 since we merged pull request #149
* We added a hack to the code of one of our dependencies in pull request #148
Bundler is now automatically installed when using Ruby 2.6, so the rubies task won't install it, and so we don't have to specify the version anymore.
Remove a no longer necesary hack we added to the code of one of our dependencies.
=> Don't force the bundler version

roles/system/tasks/tools.yml
* Continues pull request #149
The `shared-mime-info` package is required by the version of mimemagic CONSUL now uses. In the end it looks like we won't be able to remove the mimemagic dependency for a while because both paperclip and caxlsx depend on it, so we need to install this package.
While most GNU/Linux distributions install it by default, some production servers might not have it installed.
Make sure the installer runs on systems where the `shared-mime-info` package has not been installed.
=> Explicitly install shared-mime-info

roles/letsencrypt/tasks/main.yml
* Closes #183
Make sure the installer runs on Ubuntu 20.04 when a domain is configured and so an SSL certificate will be installed using Certbot.
=> Fix certbot installation on Ubuntu 20.04

roles/nginx/templates/consul_vhost.j2
* We introduced several Nginx templates in commit c01f67ec1
In commit c01f67ec1 we introduced several nginx templates. Two of them had this configuration, and one of them didn't.
We chose the one which didn't have this configuration for unrelated reasons, and didn't realize this configuration was missing until now.
Rails already generates a gzipped version of our assets when running `rake assets:precompile`, so the Nginx configuration is the only code we need to change to enable this feature.
* Make CONSUL websites load faster
In CONSUL version 1.3.0, the size of the uncompressed JavaScript file is 1.63MB, while the gzipped file size is 478KB. Similarly, the size of the uncompressed CSS file is 538KB, while the gzipped file size is 97KB.
So, in all, with this change the size of the …
=> Serve compressed CSS and JavaScript assets

README.md, group_vars/all, hosts.example
I ran into the issue of needing to change the SSH key used and had to dig though the open Issues in order to figure out where I was supposed to add the location of my SSH key. At first I thought I was supposed to set the `ansible_ssh_private_key_file` variable in `hosts`, but that did not seem to work - I was still running into the `could not locate file in lookup: ~/.ssh/id_rsa.pub` issue. I finally came across [this issue](https://github.com/consul/installer/issues/161) and learned that I was supposed to edit the variable in `group_vars/all`, which worked. 
(gotta admit, I am not familiar with Ansible, this might have been a non-issue for someone who is very comfortable with Ansible playbooks)
I added a line about this to the README, in case anyone else runs into the same issue.
=> Add ansible key to group_vars

.github/workflows/tests.yml, README.md
* Stop testing on unmaintained distributions that new CONSUL installations won't/shouldn't even consider
=> Drop support for Ubuntu 16.04

README.md, group_vars/all, roles/errbit/tasks/main.yml, roles/letsencrypt/tasks/main.yml, roles/nginx/tasks/main.yml, roles/user/tasks/main.yml, user.yml
* Makes it easier to do changes related to issue #141
* A typo in the `user.yml` was added in pull request #167
* Make it easier to change the group used by the deploy user
* Fix a typo in a condition which caused it not to be correctly evaluated when the deploy user isn't the default one
=> Allow configuring the group used by the deploy user

README.md, roles/errbit/tasks/main.yml, roles/errbit/templates/UserGemfile, roles/folder_structure/tasks/main.yml
:warning: Don't merge until we release CONSUL 1.4.0. When we release version 1.4.0, change the `roles/folder_structure/tasks/main.yml` file so it uses the `1.4.0` tag instead of the `master` branch.
* We use a Ruby 2.7 (which includes Bundler 2) since include consul/consul#4662
* The idea to use bigdecimal 1.4.4 comes from errbit/errbit#1508
* Our [test run #95](https://github.com/consul/installer/runs/3843048951) shows the way the installer failed when using Ruby 2.7
* Our [test run #96](https://github.com/consul/installer/actions/runs/1321938559) shows how the installer works fine with Ruby 2.7 after the changes in this pull request
* Install the latest stable version of CONSUL.
* Make Errbit compatible with the version of Ruby included in CONSUL 1.4.0
* Use Bundler 2 in Errbit, just …
=> Install CONSUL version 1.4.0

README.md, roles/folder_structure/tasks/main.yml
:warning: Don't merge until we release CONSUL 1.4.1. When we release version 1.4.1, change the `roles/folder_structure/tasks/main.yml` file so it uses the `1.4.1` tag instead of the `master` branch.
* Merge after we release version 1.4.1 in consul/consul#4749
=> Install CONSUL version 1.4.1

roles/puma/tasks/main.yml
* The failing tests when this code isn't used can be seen in our [test run #117](https://github.com/consul/installer/actions/runs/1619896844)
Avoid a `connect() to puma.sock failed (13: Permission denied) while connecting to upstream` error in the final steps of the installer when running the tests with Github Actions.
The master branch correctly run the tests a month ago, but not anymore, so maybe something has changed in the Ubuntu images provided by Github Actions.
I haven't been able to reproduce this issue on production; the added code is probably redundant in this scenario.
=> Make sure Nginx has write access to the puma socket 

.github/workflows/debian.yml, .github/workflows/ubuntu.yml, README.md, roles/postgresql/tasks/main.yml, roles/system/tasks/tools.yml
* Debian is one of the systems mentioned in issue #16
* Increase the number of systems where the installer can be run
We aren't enabling Errbit for Debian because Debian [no longer includes MongoDB](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947743).
=> Add support for Debian Buster and Debian Bullseye

roles/errbit/tasks/main.yml, roles/errbit/templates/UserGemfile
* The code adding Ruby 2.7 to Errbit was added in pull request #185
* Errbit added support for Ruby 2.7 in https://github.com/errbit/errbit/pull/1508
=> Remove code adding Ruby 2.7 compatibility to Errbit

roles/rails/tasks/main.yml
The previous code was only updating the key `server_name` for the last occurrence, so only for `production`.
It was not working for `staging` or `preproduction` environments.
=> Set server_name in secrets.yml correctly

group_vars/all, roles/errbit/tasks/main.yml, roles/errbit/templates/errbit.service
* Errbit updated Puma in errbit/errbit#1520
* Puma removed support for the `--daemon` option in Puma 5.0.0 and now requires using systemd or similar
* Make sure it's possible to run Errbit with the installer
Our errbit service file is based on the [Puma documentation to configure systemd](https://github.com/puma/puma/blob/21e9a4a65b3/docs/systemd.md). We're also adding a dependency on Mongodb and making sure the process runs as the user with permissions to run Errbit.
=> Use systemd to start Errbit

README.md
* Use the same format in the documentation and in the secrets.yml.example file
* Make sure the example is compatible with older versions of CONSUL
=> Make SMTP settings example consistent

roles/errbit/tasks/main.yml
* The solution was suggested in a [comment in the mini_racer issue 243](https://github.com/rubyjs/mini_racer/issues/243#issuecomment-1076909827)
* It looks like this issue will be solved when rubygems/rubygems#4488 is merged
Errbit has recently updated its mini_racer dependency to version 0.6.2, which apparently can't be installed on Ubuntu with our current Bundler settings.
=> Fix mini_racer compilation when installing Errbit

.github/workflows/kanban.yml
* Continues pull request #198
* Make sure forks don't run a task that only makes sense for the main CONSUL repository
=> Don't run kanban assignment on forks

README.md, roles/folder_structure/tasks/main.yml
~~:warning: Don't merge until we release CONSUL 1.5.0. When we release version 1.5.0, change the roles/folder_structure/tasks/main.yml file so it uses the 1.5.0 tag instead of the master branch.~~
* Merge after we release version 1.5.0 in consul/consul#4852
=> Install CONSUL version 1.5.0

group_vars/all
* The machine learning data folder was added to Capistrano's shared folders in consul/consul#4585
* We added this folder to Capistrano's shared folders in consul/consul@73a0a2100
* Make machine learning scripts work on new CONSUL installations
* Make Active Storage use a shared folder on new CONSUL installations
=> Add missing shared public folders

roles/postgresql/tasks/main.yml, roles/rails/templates/database.yml
* These changes are needed to make the installer compatible with multitenancy consul/consul#4030
* Install extensions on a shared schema so they're available to all tenants
=> Install PostgreSQL extensions on a shared schema

roles/rails/tasks/main.yml
We were getting a couple of warnings when running `bundle install --path {{ shared_dir }}/bundle --without development test`:
> [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path '/home/deploy/consul/shared/bundle/'`, and stop using this flag
> 
> [DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'development test'`, and stop using this flag
* Use the new way to configure the arguments given to Bundler so it keeps working in the future
=> Update bundler arguments configuration 

.github/workflows/ubuntu.yml, README.md
* Remove support for a distribution that is no longer supported by Ubuntu or GitHub Actions
Tests for Debian fail, but they also fail on the master branch, so the reason why they fail isn't related to this pull request. This issue is fixed in pull request #217.
=> Remove official support for Ubuntu 18.04

roles/errbit/tasks/main.yml
* Errbit specifies the needed Ruby version since https://github.com/errbit/errbit/pull/1528
* Make it possible to install Errbit in Consul installations using Ruby 3.x
=> Install the Ruby version needed by Errbit

roles/queue/tasks/main.yml
* We changed the way Consul runs DelayedJob processes in consul/consul#5146
* Use the same command to run delayed job as we use in Capistrano
=> Restart DelayedJob workers after they crash

.github/workflows/debian-bullseye.yml, .github/workflows/debian-buster.yml
* #222 
With this change, we will run Debian tests in separate workflows by version, so if one job from a Debian version fails, it does not cancel all the other jobs.
We keep the failing buster tests because the installer works fine on real servers. It only fails in the CI.
We can revert this changes when we solve the CI error with the Debian Buster.
=> Split Debian tests by Debian version

app.yml, galaxy/yatesr.timezone/tasks/main.yml, group_vars/all, roles/errbit/tasks/main.yml, roles/errbit/templates/errbit.service, roles/folder_structure/tasks/main.yml, roles/nodejs/tasks/main.yml, roles/puma/tasks/main.yml, roles/queue/tasks/main.yml, roles/rails/tasks/main.yml, roles/system/tasks/main.yml, roles/system/tasks/tools.yml
* consuldemocracy/consuldemocracy#5158
* consuldemocracy/consuldemocracy#5159
**Do not merge until the Consul Democracy 2.1.0 release.**
Consul Democracy has added a `.node-version` file in version 2.1.0, and now it installs the version defined there when deploying with Capistrano and installs NPM packages for that version.
So we're doing the same when running the installer.
1. Install `FNM` for the deploy user
2. Install the `nodejs` version defined in consuldemocracy/consuldemocracy using `FNM`.
3. Install the `nodejs` application dependencies defined in consuldemocracy application `package.json` using `NPM`.
4. Update rails commands so the application finds the proper `nodejs` binaries
The `FNM` installer adds the following entry to the `deploy_user` `.bashrc` file:
```
export …
```
=> Install specific nodejs version

group_vars/all, roles/folder_structure/tasks/main.yml, roles/puma/tasks/main.yml, roles/puma/templates/puma.service, roles/specs/tasks/main.yml, roles/system/tasks/tools.yml
* We're upgrading Puma to a version that requires systemd in consuldemocracy/consuldemocracy#5178
I haven't found a way to run systemd services when testing the installation on Debian with GitHub Actions (not even when using [Docker images with systemd](https://github.com/trfore/docker-debian11-systemd/)). So, for now, we're not testing whether Puma starts correctly on Debian, which means we won't notice it if Puma doesn't start correctly on Debian in the future.
=> Use systemd to start Puma

.github/workflows/ubuntu.yml, README.md, roles/user/tasks/main.yml
* #204
* Add Ubuntu 22.04 support
* Do not install Errbit In Ubuntu 22.04 
* Ensure deploy_user home has the correct permissions
=> Add Ubuntu 22.04 support

.github/workflows/debian.yml, README.md, roles/postgresql/tasks/main.yml
* Make it possible to install Consul Democracy in the latest stable version of Debian
=> Add support for Debian Bookworm

group_vars/all, roles/rails/tasks/main.yml
This PR depends on:
* consuldemocracy/consuldemocracy#5318
Allow users to set up the application timezone from the installer like we do with the server timezone.
=> Set the application timezone

roles/puma/tasks/main.yml, roles/puma/templates/puma.service, roles/puma/templates/puma.socket
* https://github.com/consuldemocracy/consuldemocracy/pull/5372
Avoid using FNM in the Puma system service ExecStart command, which fixes issues regarding stopping/restarting the service and graceful restarts.
Please take a look at the referenced PR description for more details.
=> Enable graceful appication restarts

.github/workflows/debian.yml, .github/workflows/ubuntu.yml, README.md, app.yml, galaxy/yatesr.timezone/tasks/main.yml, group_vars/all, roles/errbit/tasks/main.yml, roles/errbit/templates/errbit.service, roles/folder_structure/tasks/main.yml, roles/nodejs/tasks/main.yml, roles/postgresql/tasks/main.yml, roles/puma/tasks/main.yml, roles/puma/templates/puma.service, roles/puma/templates/puma.socket, roles/queue/tasks/main.yml, roles/rails/tasks/main.yml, roles/specs/tasks/main.yml, roles/system/tasks/main.yml, roles/system/tasks/tools.yml, roles/user/tasks/main.yml
:warning: Replace the `master` branch with the `2.1.0` tag once Consul Democracy 2.1.0 is released.
=> Install Consul Democracy 2.1.0

README.md
* We renamed the `tests` workflow to `ubuntu` in commit f346954ea from pull request #190
* Correctly show the status of the test suite in the README file
For unknown reasons, the Debian badge shows that the build failed even when it passed, so for now we're only showing the one for Ubuntu.
=> Update tests status badge in README

roles/errbit/tasks/main.yml, roles/nodejs/tasks/main.yml, roles/queue/tasks/main.yml, roles/rails/tasks/main.yml
* We introduced FNM in pull request #223
* We did similar changes for Capistrano deployments in consuldemocracy/consuldemocracy@bb20e8e2bd
* Simplify the code executing Ruby commands than don't depend on Node.js
* Simplify the code executing Node.js commands than don't depend on Ruby
* Make the commands in the installer more consistent with the commands in Capistrano
=> Only use fnm exec when necessary 

.github/dependabot.yml
* We're doing the exact same thing for the main project in consuldemocracy/consuldemocracy#5611
* Make it easier to maintain our github actions dependencies
=> Use dependabot to update github actions dependencies

.github/workflows/debian.yml, .github/workflows/ubuntu.yml, README.md
* Point out that we now officially support installing Consul Democracy on the latest Ubuntu LTS version
We haven't had to change anything in the installer; we've only had to change the github actions workflow.
=> Add support for Ubuntu 24.04

galaxy/rvm.ruby/tasks/rvm.yml
* This was consistently failing on our CI with Ubuntu 22.04 and Ubuntu 24.04 since a few weeks ago; for example in our [test run 392, job 2](https://github.com/consuldemocracy/installer/actions/runs/11180060085/job/31082011569)
* Avoid an error with RVM GPG keys when running the installer in our CI
=> Fix the import of RVM GPG keys

.github/workflows/ubuntu.yml, README.md
* Make it clear that we don't support Ubuntu 20.04 since it's about to be deprecated
With this commit, we no longer test that Errbit is correctly installed. We might add it to other workflows in the future.
=> Remove support for Ubuntu 20.04

roles/puma/templates/puma.service
Related PR's: consuldemocracy/consuldemocracy#6022
Replace the hardcoded SyslogIdentifier=puma with a dynamic value using the "puma_service_unit_name" variable. This ensures consistency with the capistrano3-puma gem, which uses the same value to name systemd units and logs (e.g. "puma_consul_production").
This aligns the installer with the capistrano3-puma configuration used in the consuldemocracy application, avoiding mismatches or duplicated identifiers across deployments.
=> Align SyslogIdentifier in puma.service template with Capistrano defaults
