consuldemocracy/installer

- .gitignore
- README.md
- consul.yml
- group_vars/all
- hosts
- hosts.example
- roles/capistrano/tasks/main.yml
- roles/capistrano/templates/deploy-secrets.yml
- roles/capistrano/templates/deploy.rb
- roles/capistrano/templates/development.rb
- roles/rails/templates/development.rb
- roles/unicorn/tasks/main.yml
- roles/unicorn/templates/unicorn.rb
What
===
Add configuration for initial deploy with Capistrano
> Add Capistrano configuration

- README.md
References
===
**Issue:** https://github.com/consul/installer/issues/13
What
===
Run playbook with verbose option
Why
===
Until the playbook is _complete_ it's helpful to see what every action is doing
> Run playbook with verbose option

- README.md
- group_vars/all
- roles/capistrano/tasks/main.yml
References:
===
**Issue:** https://github.com/consul/installer/issues/7
Context
===
Emails are delivered correctly, however email links do not have the correct host
What
===
- Add host configuration to correctly render email links
- Add email configuration to README
> Fix email configuration

- roles/system/tasks/tools.yml
References
===
**Issue: https://github.com/consul/installer/issues/15**
Context
===
In order to upload images we need a system image processing library
What
===
Install ImageMagick
> Install ImageMagick

- consul.yml
- group_vars/all
- roles/email/tasks/main.yml
What
===
Setup default configuration to send emails via SMTP
Why
===
This is a common pitfall and it was raising a nasty 500 error if not configured properly
Using a demo SMTP server for first installations
Please update with your own SMTP server credentials before launching 😌
> Add SMTP configuration

- README.md
Objectives
===
Add email documentation and solutions for known email gotchas.
> Add email documentation

- README.md
Objectives
===
Add documentation for Ubuntu users to install the following in their local machines: 
- Ansible
- Python
- CONSUL for development environments
> Add documentation to setup local Ubuntu machine

- README.md
A little bit more detailed messages in the installation steps.
> Add more detailed messages for installation steps

- consul.yml
- roles/nginx/handlers/main.yml
- roles/nginx/tasks/main.yml
Not sure how this was working before...
> perform the nginx tasks with sudo

- .travis.yml
- README.md
- app.yml
- roles/postgresql/tasks/main.yml
- roles/specs/tasks/main.yml
- roles/system/tasks/main.yml
Continuous Integration, the process of running all specs when the code changes, is a beautiful and necessary feature to make the code robust.
Setup Continuous Integration with Travis for the Installer.
Big thanks to @afeld for [leading the way](https://github.com/consul/installer/pull/75) in this integration 🎉👏
> Add Integration with Travis CI

- README.md
- galaxy/rvm.ruby/defaults/main.yml
- group_vars/all
- roles/rails/tasks/main.yml
* CONSUL started using Ruby 2.4.6 in consul/consul#3627, and Ruby 2.4.9 in consul/consul#3785
* Closes #10
* Use the same Ruby version CONSUL uses
> Upgrade Ruby to 2.4.9

- app.yml
- capistrano.yml
- roles/capistrano/tasks/main.yml
- roles/folder_structure/tasks/main.yml
- roles/letsencrypt/tasks/main.yml
- roles/puma/tasks/main.yml
- roles/queue/tasks/main.yml
- roles/rails/tasks/main.yml
* Closes #51 (if that issue is still valid)
* Avoid potential security risks or permission problems when configuring and running CONSUL
* Simplify the code; we can now omit all `owner:` and `group:` options we were adding when creating files as root
> Set up CONSUL as a regular user

- README.md
Move screencasts from BaseCamp to YouTube.
> Update screencasts url

- README.md
* Update documentation regarding our recent changes in SMTP configuration
> Update SMTP documentation 

- roles/folder_structure/tasks/main.yml
* Continues pull request #115
* Make first deployment with Capistrano faster
* Use Capistrano's folder conventions
> Clone git repository where Capistrano expects it

- README.md
- app.yml
- galaxy/rvm.ruby/defaults/main.yml
- group_vars/all
- roles/ruby/tasks/main.yml
* Closes #118
* Make sure the installer keeps working when the Ruby version used by CONSUL changes
> Install Ruby based on CONSUL's .ruby-version

- README.md
- roles/folder_structure/tasks/main.yml
Download latest stable version of CONSUL (currently version 1.1.0)
> Synchronize installer version with CONSUL version

- .travis.yml
- README.md
- roles/system/tasks/main.yml
Related PRs:
- [Add staging configuration #4](https://github.com/voodoorai2000/installer/pull/4)
- [Add smtp settings for staging environment on secrets #3870](https://github.com/consul/consul/pull/3870)
Allow to install to staging environment with installer
Recover commits from [Add staging configuration #4](https://github.com/voodoorai2000/installer/pull/4)
> Add Staging configuration instructions

- .travis.yml
- README.md
- roles/postgresql/tasks/main.yml
- roles/system/tasks/main.yml
- roles/system/tasks/tools.yml
* Closes #87
Make it possible to install CONSUL on servers running Ubuntu 18.04.
> Add Ubuntu 18.04 compatibility

- README.md
- roles/folder_structure/tasks/main.yml
* Merge after we release version 1.2.0 in consul/consul#4113
> Install CONSUL version 1.2.0

- README.md
- group_vars/all
- roles/rails/templates/database.yml
* Configure the `database.yml` file using the values users set in `group_vars/all`
* Remove unused variables
> Use database variables in database.yml

- README.md
- roles/folder_structure/tasks/main.yml
- roles/rails/tasks/main.yml
* Merge after we release version 1.3.0 in consul/consul#4391
> Install CONSUL version 1.3.0

- README.md
- roles/folder_structure/tasks/main.yml
* Merge after we release version 1.3.1 in consul/consul#4536
> Install CONSUL version 1.3.1

- group_vars/all
* See rvm/rvm#5096 for details
* Closes #133
> Update servers to get RVM GPG keys

- README.md
https://github.com/consul/installer/issues/141
> Clarify sudo and wheel for Ubuntu

- .github/workflows/kanban.yml
* We're doing the same thing we've done in consul/consul#4853
> Add kanban automation for new pull requests

- README.md
- roles/folder_structure/tasks/main.yml
* We released version 2.0.1 in consuldemocracy/consuldemocracy#5177
* Install the latest stable version of CONSUL
> Install Consul Democracy version 2.0.1

- README.md
- roles/folder_structure/tasks/main.yml
* Depends on consuldemocracy/consuldemocracy#5428
> Install Consul Democracy version 2.1.1

- README.md
- roles/folder_structure/tasks/main.yml
- roles/queue/tasks/main.yml
* Depends on #241
* Depends on consuldemocracy/consuldemocracy#5586
> Install Consul Democracy version 2.2.0

- README.md
- roles/folder_structure/tasks/main.yml
* Depends on consuldemocracy/consuldemocracy#5727
> Install Consul Democracy version 2.2.1

- README.md
- roles/folder_structure/tasks/main.yml
* Depends on consuldemocracy/consuldemocracy#5743
> Install Consul Democracy version 2.2.2

- README.md
- roles/folder_structure/tasks/main.yml
* Depends on consuldemocracy/consuldemocracy#5846
> Install Consul Democracy version 2.3.0

- README.md
- roles/folder_structure/tasks/main.yml
* Depends on consuldemocracy/consuldemocracy#5949
> Install Consul Democracy version 2.3.1
